# Generated by Django 5.2.6 on 2025-09-09 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('footwear', 'Footwear'), ('jersey', 'Jersey'), ('shin guard', 'Shin Guard'), ('gloves', 'Gloves'), ('other', 'Other')], default='other', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=10)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
