# Generated by Django 5.2.6 on 2025-10-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_news_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
