# Generated by Django 5.2.6 on 2025-09-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_news_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Product',
        ),
    ]
