# Generated by Django 5.2.6 on 2025-10-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bola'),
        ('main', '0005_product_user'),
    ]

    operations = [
    ]
